---
apiVersion: "v1"
data:
  jenkins-gogs-email: "gogsadmin@fabric8.local"
  jenkins-gogs-password: "RedHat$1"
  jenkins-gogs-user: "gogsadmin"
  pipeline-elasticsearch-protocol: "http"
  pipeline-elasticsearch-host: "elasticsearch"
  project-version: ${project.version}
kind: "ConfigMap"
metadata:
  annotations:
    fabric8.jenkins/summary: "[Jenkins](http://jenkins-ci.org/) extendable open source\
      \ continuous integration server"
    description: "Jenkins CI is a leading open-source continuous integration server.\
      \ Built with Java, it provides 985 plugins to support building and testing virtually\
      \ any project.\n\n[http://jenkins-ci.org/](http://jenkins-ci.org/)"
    fabric8.jenkins/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg"
    fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n \
      \   \"PIPELINE_ELASTICSEARCH_PROTOCOL\" : {\n      \"type\" : \"string\"\
      ,\n      \"description\" : \"Protocol used to connect to elasticsearch\",\n\
      \      \"default\" : \"http\"\n    },\n    \"JENKINS_GOGS_USER\" : {\n     \
      \ \"type\" : \"string\",\n      \"description\" : \"The user name for Jenkins\
      \ to login to Gogs\",\n      \"default\" : \"gogsadmin\"\n    },\n    \"JENKINS_GOGS_PASSWORD\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The password\
      \ for Jenkins to login to Gogs\",\n      \"default\" : \"RedHat$1\"\n    },\n\
      \    \"PIPELINE_ELASTICSEARCH_HOST\" : {\n      \"type\" : \"string\",\n   \
      \   \"description\" : \"Elasticsearch hostname used for pipeline events\",\n\
      \      \"default\" : \"elasticsearch\"\n    },\n    \"JENKINS_GOGS_EMAIL\" :\
      \ {\n      \"type\" : \"string\",\n      \"description\" : \"The email address\
      \ of the Jenkins user on Gogs\",\n      \"default\" : \"gogsadmin@fabric8.local\"\
      \n    }\n  }\n}"
  labels: {}
  name: "jenkins"
