---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    fabric8.io/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-devops/master/jenkins/src/main/fabric8/icon.svg"
  name: "jenkins"