---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    project: "jenkins"
    provider: "fabric8"
    expose: "false"
  annotations:
    fabric8.io/app-menu: development
  name: "jenkins"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "jenkins"
    provider: "fabric8"
